In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split

In [29]:
df = pd.read_csv("boston.csv")

## Polynom Regr

In [30]:
X = df.drop("PRICE", axis=1)
y= df["PRICE"]

In [31]:
from sklearn.preprocessing import PolynomialFeatures
poly_conv = PolynomialFeatures(degree=2, include_bias=False)
poly_features = poly_conv.fit_transform(X)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.25, random_state=9)

## Data Scaling

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
scaler = StandardScaler()

In [35]:
scaler.fit(X_train)

StandardScaler()

In [36]:
X_train = scaler.transform(X_train)

In [37]:
X_test = scaler.transform(X_test)

In [38]:
X_train

array([[-0.39991762, -0.50505281, -1.22053449, ...,  0.52976211,
        -1.04307369, -0.82175909],
       [-0.40869137,  2.91689161, -1.42037434, ...,  0.52976211,
        -1.06286308, -0.82627174],
       [-0.40446862, -0.50505281,  0.22939843, ...,  0.4897126 ,
        -0.6570016 , -0.70349173],
       ...,
       [-0.37094859, -0.50505281,  2.09943264, ..., -0.19674491,
         2.07251469,  2.21563925],
       [-0.41141958,  2.91689161, -1.34889878, ...,  0.40981499,
        -0.78580383, -0.74573447],
       [ 0.58551961, -0.50505281,  0.99812544, ...,  0.52976211,
         1.90858872,  1.4361834 ]])

## Ridge Regr

In [39]:
from sklearn.linear_model import Ridge

In [49]:
ridge_model = Ridge(alpha=0.1)

In [50]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=0.1)

In [51]:
ridge_pred = ridge_model.predict(X_test)

In [52]:
MAE = mean_absolute_error(y_test,ridge_pred)
MSE = mean_squared_error(y_test,ridge_pred)
R2 = r2_score(y_test, ridge_pred)
RMSE = np.sqrt(MSE)

print("MAE  : ", MAE)
print("RMSE : ", RMSE)
print("R2 : ",R2)

MAE  :  2.717933505017278
RMSE :  3.6852761145425372
R2 :  0.8475024591915228


##### For selecting alpha

In [53]:
from sklearn.linear_model import RidgeCV

In [54]:
ridge_cv = RidgeCV(alphas=(0.001,0.01,0.1, 1.0, 10.0), scoring="neg_mean_absolute_error")

In [55]:
ridge_cv.fit(X_train,y_train)

RidgeCV(alphas=(0.001, 0.01, 0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [56]:
ridge_cv.alpha_

0.1

In [57]:
from sklearn.linear_model import LassoCV

In [58]:
lasso_cv = LassoCV(eps=0.1,n_alphas=100,cv=5)

In [60]:
lasso_cv.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [61]:
lasso_cv.alpha_

0.6828621619826487

In [62]:
lasso_cv.coef_

array([-0.        ,  0.        , -0.        ,  0.        , -0.        ,
        0.        , -0.        , -0.        , -0.        , -0.        ,
       -1.04569675,  0.        , -0.        , -0.        ,  0.        ,
       -0.        ,  0.33106637, -0.        , -0.33416547, -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.        , -0.        ,  0.        ,
       -0.        , -0.        , -0.        , -0.06580273, -0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        ,  0.        , -0.        ,  3.49092082, -0.  

###### Ridge kullanmadığı katsayıları çok düşük seviyelere çekerken lasso ise belli bir seviyenin altındaki katsayıları görmezden gelir.

In [64]:
lasso_pred = lasso_cv.predict(X_test)

In [65]:
MAE = mean_absolute_error(y_test,lasso_pred)
MSE = mean_squared_error(y_test,lasso_pred)
R2 = r2_score(y_test, lasso_pred)
RMSE = np.sqrt(MSE)

print("MAE  : ", MAE)
print("RMSE : ", RMSE)
print("R2 : ",R2)

MAE  :  3.2682953671193324
RMSE :  4.668293273898158
R2 :  0.7552971435685456


##### ElasticNet

In [68]:
from sklearn.linear_model import ElasticNetCV

In [69]:
elasticnet_model = ElasticNetCV(l1_ratio=[0.01, 0.1, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99, 1], tol=0.01)

##### L1 Lasso, L2 ridge

In [70]:
elasticnet_model.fit(X_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:664: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 297.57648195114825, tolerance: 272.02624026402634
  model = cd_fast.enet_coordinate_descent_gram(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:664: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 288.04576871037534, tolerance: 272.02624026402634
  model = cd_fast.enet_coordinate_descent_gram(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:664: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 299.8658069035487, tolerance: 235.00122244224423
  model = cd_fast.enet_coo

ElasticNetCV(l1_ratio=[0.01, 0.1, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99, 1], tol=0.01)

In [71]:
elasticnet_model.l1_ratio_

0.9

In [72]:
elasticnet_model.coef_

array([ 2.19070569e+00, -5.95956868e+00,  3.78137424e+00,  1.86279121e+00,
        1.86101372e+00,  3.69597408e+00,  1.57451886e+00, -8.79212823e-02,
        5.06404175e-02,  0.00000000e+00,  0.00000000e+00,  5.55612670e+00,
       -2.06627814e+00,  1.04568999e+00,  3.41174452e-01,  0.00000000e+00,
        2.57660615e+00, -2.70355387e+00, -0.00000000e+00, -0.00000000e+00,
       -1.34227460e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -8.10523248e-01,  0.00000000e+00,  1.33729471e+00, -0.00000000e+00,
       -3.10713142e-01,  0.00000000e+00,  1.14907275e+00, -1.83303869e-02,
       -8.32740974e-01, -1.27376368e-03,  1.93912312e+00,  2.71495190e+00,
        0.00000000e+00, -6.98218352e-01,  4.12604078e-01, -0.00000000e+00,
        1.11097022e+00, -6.92223592e-01,  3.94393583e-01, -9.42774097e-01,
       -5.70316341e-01,  0.00000000e+00, -2.19451413e+00,  5.21944011e-01,
       -3.01461654e+00,  5.94071392e-01, -3.61822166e+00, -4.14702939e+00,
        2.29463480e-01,  

In [73]:
elastic_pred = elasticnet_model.predict(X_test)

In [75]:
MAE = mean_absolute_error(y_test,elastic_pred)
MSE = mean_squared_error(y_test,elastic_pred)
R2 = r2_score(y_test, elastic_pred)
RMSE = np.sqrt(MSE)

print("MAE  : ", MAE)
print("RMSE : ", RMSE)
print("R2 : ",R2)

MAE  :  2.4684630122956785
RMSE :  3.3977658046265673
R2 :  0.8703687651604619
